In [20]:
import sklearn.datasets as datasets
import pandas as pd
iris=datasets.load_iris()
X=pd. DataFrame (iris.data, columns=iris.feature_names)
y=iris.target
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

from sklearn.linear_model import LogisticRegression

from sklearn import metrics
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
predictions=logreg.predict(x_test)
from sklearn.metrics import classification_report,confusion_matrix
print (confusion_matrix(y_test, predictions))
print (classification_report (y_test, predictions) )



[[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.94      0.97        18
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [17]:
import numpy 
from sklearn import datasets, metrics
from sklearn.naive_bayes import GaussianNB 
X, y=datasets. load_iris (return_X_y=True)
#print (X)
#print(y)

X_train=X[range(0, 150,2), :]
y_train=y[range (0,150,2)]
X_test=X[range (1,150,2), :]
y_test=y[range (1,150,2)]

clf=GaussianNB () #creating instance of a classifier #BernoullinB() for Bernoulins
#Multinomia NB() for Multinomia2NB ()

clf.fit(X_train, y_train)
prediction=clf.predict (X_test) #predict using the learnt classifier
print("****# Predictions***")
print (prediction)
print("*****")

print("Accuracy:",metrics.accuracy_score(y_test, prediction, normalize=True))
print (metrics.classification_report (y_test, prediction))
print (metrics.confusion_matrix(y_test, prediction))

****# Predictions***
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 2]
*****
Accuracy: 0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]
