<html>
    <body>
        <p style="font-size:30px;text-align:center;"><b>Practical 5</b></p>
        <p style="font-size:20px;text-align:center;">Name: KHARE PRATYUSH</p>
        <p style="font-size:20px;text-align:center;">Roll-No: 20BCE519</p>
        <p style="font-size:20px;text-align:center;">Course Name: Machine Learning (2CS501)</p>
    </body>
</html>
    

<p style="font-size:1.2em"><b> Aim: Naive-Bayes – Multivariate Bernoulli, Multinomial and Gaussian using sklearn, KNN using sklearn</b></p>

# Gaussian Naive Bayes

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn import datasets,metrics
from sklearn.naive_bayes import GaussianNB
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

X,y=datasets.load_iris(return_X_y=True)

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.5,random_state=0)

gnb=GaussianNB()

gnb.fit(X_train, y_train)

prediction = gnb.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test,prediction,normalize=True))

print("\nPrediction:\n",prediction)

print("\nClassification Report:\n",metrics.classification_report(y_test,prediction))

cm = metrics.confusion_matrix(y_test, prediction)

print("Confusion Matrix is as follows: \n  ",cm)



Accuracy: 0.9466666666666667

Prediction:
 [2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1 1 2 1 1 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0
 1]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      1.00      0.94        30
           2       1.00      0.83      0.91        24

    accuracy                           0.95        75
   macro avg       0.96      0.94      0.95        75
weighted avg       0.95      0.95      0.95        75

Confusion Matrix is as follows: 
   [[21  0  0]
 [ 0 30  0]
 [ 0  4 20]]


# Multivariate Bernoulli 

In [13]:
import urllib
from sklearn.naive_bayes import BernoulliNB

url="https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"

raw_data= urllib.request.urlopen(url)
data= np.loadtxt(raw_data,delimiter=',')

x=data[:,0:48]
y=data[:,-1]

xtrain, xtest, ytrain, ytest=train_test_split(x,y, test_size=0.3, random_state=50)

bernoulli = BernoulliNB(binarize=True)
bernoulli.fit(xtrain,ytrain)
ypred=bernoulli.predict(xtest)
print(pd.Series(ypred).head())

print("\nAccuracy : \n",metrics.accuracy_score(ytest,ypred,normalize=True))
print("\nConfusion Matrix : \n",metrics.confusion_matrix(ytest, ypred))
print("\nClassification Report : \n",metrics.classification_report(ytest,ypred))


0    0.0
1    0.0
2    1.0
3    0.0
4    0.0
dtype: float64

Accuracy : 
 0.8602461984069515

Confusion Matrix : 
 [[758  94]
 [ 99 430]]

Classification Report : 
               precision    recall  f1-score   support

         0.0       0.88      0.89      0.89       852
         1.0       0.82      0.81      0.82       529

    accuracy                           0.86      1381
   macro avg       0.85      0.85      0.85      1381
weighted avg       0.86      0.86      0.86      1381



# Multinomial Naive Bayes

In [7]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
datasets='https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv'

sms=pd.read_table(datasets,header=None,names=['Label','Message'])
sms['Label_Number']=sms.Label.map({'ham':0,'spam':1})


X=sms.Message
y=sms.Label_Number

X_train=X[0:4179]
X_test=X[4179:]
y_train=y[0:4179]
y_test=y[4179:]


vector = CountVectorizer()
vector.fit(X_train)

X_train_dtm = vector.transform(X_train)
X_test_dtm = vector.transform(X_test)

MNB=MultinomialNB()
MNB.fit(X_train_dtm,y_train)

y_pred=MNB.predict(X_test_dtm)

print("Accuracy:",metrics.accuracy_score(y_test,y_pred,normalize=True))

print("\nPrediction:\n",y_pred)

print("\nClassification Report:\n",metrics.classification_report(y_test,y_pred))
print("Confusion Matrix :\n",metrics.confusion_matrix(y_test, y_pred))




Accuracy: 0.9856424982053122

Prediction:
 [0 0 0 ... 0 0 0]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1211
           1       0.96      0.93      0.94       182

    accuracy                           0.99      1393
   macro avg       0.97      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393

Confusion Matrix :
 [[1203    8]
 [  12  170]]


# KNN Using Sklearn

In [10]:
from sklearn import neighbors,datasets

X,y=datasets.load_iris(return_X_y=True)

X_train=X[range(0,150,2),:]
y_train=y[range(0,150,2)]

X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]

n_neighbors=3

weights='distance'

clf=neighbors.KNeighborsClassifier(n_neighbors)

clf.fit(X_train,y_train)

prediction=clf.predict(X_test)

print(prediction)

print("Accuracy=",metrics.accuracy_score(y_test,prediction,normalize=True))

print("Classification Report:\n",metrics.classification_report(y_test,prediction))

print("Confusion Matrix :\n",metrics.confusion_matrix(y_test, prediction))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
Accuracy= 0.96
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.96      0.92      0.94        25
           2       0.92      0.96      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

Confusion Matrix :
 [[25  0  0]
 [ 0 23  2]
 [ 0  1 24]]
